
[tools]
node = "lts"
bun = "latest"
pnpm = "latest"
codex = "latest"
claude = "latest"
fzf = "latest"
yazi = "latest"
lazydocker = "latest"

uv = "latest"
"pipx:podman-compose" = "latest"
"pipx:yt-dlp" = "latest"
"pipx:powerline-status" = "latest"

rust = "latest"
cargo-binstall = "latest"
"cargo:eza" = "latest"
"cargo:ripgrep" = "latest"
"cargo:bat" = "latest"
"cargo:fd-find" = "latest"
"cargo:bottom" = "latest"
"cargo:tealdeer" = "latest"
"cargo:starship" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:zoxide" = "latest"

[settings]

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true
